### ISSUE TITLE
数据集的相关问题

### ISSUE THREAD

**Issue by MaChao1013** [xintangjin/MLP-AMDC#1]
您好，请问AMDC的网络是同时将HSI和RGB图放入网络吗，使用的数据集是CAVE_1024吗，代码中显示的是CAVE_1024, 但是数据集下载下来不是这个，还有RGB图像的数据集有900张，谢谢

**Comment by xintangjin** [comment]
您好，是同时放进网络的，CAVE的数据我们用的是和TSA以及MST是一致的，他们提供的下载链接是网页中的链接。然后CAVE的RGB图片，我使用的是自己的合成的，下载链接是 https://pan.baidu.com/s/1GINXZM0nAe-EKlsXN0uqzA?pwd=y183    code: y183。要是RGB数据有什么问题，您随时联系我。

**Comment by MaChao1013** [comment]
感谢您的回复，我看这个cave的RGB数据集中有1000多张图，但是HSI的图片不是只有205张吗，而且双路的话应该是HSI和RGB相互对应的，请问这是怎么实现的，谢谢

**Comment by xintangjin** [comment]
总共是401张，但之前的工作只用了其中一半的样子，这个在utils数据加载里面可以看到

**Comment by MaChao1013** [comment]
请问您RGB图片是怎样生产的

**Comment by MaChao1013** [comment]
您好，还有一个我问题，我看您文章中，所对比的算法，其这些网络中一部分是单路的，请问您在比较的过程中，怎样将RGB图像加入到这些网络中的，谢谢

**Comment by xintangjin** [comment]
您好，我提供的那个RGB是合成的，其实也可以用原数据集提供的。网络中的确都是单路的，这个也是目前文章被拒的问题之一，文章还在修改重投中。

**Comment by MaChao1013** [comment]
您好，我想问一下您的RGB图像的具体合成方式，是怎样由HSI生成相对应的RGB图像的

**Comment by xintangjin** [comment]
是线性合成的，并引入了一些照明的先验，肯定是和实际采集有出入的，当然有采集设备的话最好的方式还是实际采集。
