### ISSUE TITLE
数据集相关的问题

### ISSUE THREAD

**Issue by fengyuchao97** [xintangjin/MLP-AMDC#2]
请问下您实验中 ARAD_1K 的 mask.mat 是如何获取的呀，如果可以能否向您要一下这个文件，谢谢

**Comment by xintangjin** [comment]
您好，您需要的Mask是送入网络一起训练的那个吗？如果是哪个template那个，是之前Tsa-net里面的实采得到的，我就直接用的那个，其实您可以随机生成一个都行，需要的话我发您。

**Comment by fengyuchao97** [comment]
哇，麻烦您分享一下，太感谢了，1149160349@qq.com

**Comment by fengyuchao97** [comment]
初看您的代码，不知道此处是否是小错误，请您看一下，在ARAD_1K/train_code的train.py中出现了if opt.input_setting == 'AMDC': 和 if opt.input_setting == 'DMDC': 两个版本，DMDC是否应该统一为AMDC

**Comment by xintangjin** [comment]
是的，我的代码可读性很差的，还请谅解哈。当时做这个的时候，是拿之前的那个代码改的，可能赶时间，所以有很多问题。感谢指点，还请多多包涵哈，嘿嘿。

**Comment by fengyuchao97** [comment]
要不跟您直接加个微信，fyc526338，对您这个很感兴趣，可以后续继续交流

**Comment by xintangjin** [comment]
好的，邮件已发，请查收！
