### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by MaChao1013** [xintangjin/MLP-AMDC#3]
您好，请问您在生成RGB数据集的时候，用到要SRF MATRIX 了吗，方便您给一下可以吗，真的非常非常感谢

**Comment by xintangjin** [comment]
链接：https://pan.baidu.com/s/1qYmyQ0nilQpKzGz4p6wOFQ?pwd=1w37 
提取码：1w37

**Comment by xintangjin** [comment]
链接：https://pan.baidu.com/s/1UzDlk7FbDo7QaxUJmWMN5Q?pwd=oqtl 
提取码：oqtl

**Comment by MaChao1013** [comment]
非常非常感谢，但是我打开您给的这个SRF，显示shape是（89， ），这是什么意思，另一个D700是（31， 3），数据集显示应该是（28，3）吧

**Comment by xintangjin** [comment]
SRF那个是光源的，范围在txt里面，相机那个是400nm - 700nm,需要插值

**Comment by MaChao1013** [comment]
哦哦，好的好的，非常感谢

**Comment by MaChao1013** [comment]
您问您有插值好的吗，因为我自己插值的不对，生成的RGB数据集和您的不太一样，算出来的指标也很低

**Comment by xintangjin** [comment]
链接：https://pan.baidu.com/s/1y8C3AvFGX8QjXQOpgYU1GQ?pwd=x5zb 
提取码：x5zb

**Comment by xintangjin** [comment]
RGB图片有的话直接用就行，反正也就只是个合成数据

**Comment by MaChao1013** [comment]
非常非常感谢，对，一开始我就是用的你的，但是我们导师说要用到SRF巴拉巴拉，那请问这个是不是也要乘上光源，您方便再把光源的插值结果发给我吗

**Comment by xintangjin** [comment]
已经乘过了

**Comment by MaChao1013** [comment]
所以现在的插值后的SRF直接就可以用了是吗，谢谢谢谢

**Comment by xintangjin** [comment]
没搞懂，是我那个RGB有问题吗，其实都是一种线性表达，无所谓的

**Comment by xintangjin** [comment]
我是用的之前实验室里面的代码跑的，应该是可以的

**Comment by MaChao1013** [comment]
好的好的，真的是非常非常感谢了，救命了，祝您学业顺利，恭喜发财



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tree ***@***.***&gt;
发送时间: 2024年4月29日 21:58
收件人: xintangjin/MLP-AMDC ***@***.***&gt;
抄送: MaChao1013 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xintangjin/MLP-AMDC] 数据集问题 (Issue #3)





 
我是用的之前实验室里面的代码跑的，应该是可以的
