### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Johnweii25** [xintangjin/MLP-AMDC#4]
作者您好，在AMDC.py中定义的rgb模块的类，使用了spectral_block来处理，请问这个处理方式是获取输入的rgb图像的光谱特征吗？

**Comment by xintangjin** [comment]
是的，只在第一stage的时候，CASSI和RGB两个分支独立学习光谱特征

**Comment by Johnweii25** [comment]
谢谢，你们的工作很棒！如果可以的话，可以加个联系方式吗？我的微信?:douw127

**Comment by xintangjin** [comment]
谢谢您的鼓励，我们也只是Follow了袁鑫老师、王立志老师的工作，仅仅仿真而已，我们会继续努力。
